name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜（UTC时间）执行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # 检出代码
      - uses: actions/setup-python@v2  # 设置Python环境
        with:
          python-version: '3.x'  # 选择Python版本
      - run: pip install requests  # 安装依赖
      - run: python myjob.py  # 运行你的Python脚本
